### ISSUE TITLE
vo 添加 title 属性

### ISSUE THREAD

**Issue by kaikaiiiiiii** [kaikaiiiiiii/vo#1]
\<div class="vo vo-right" id="20kqn3.ogg">
\<div class="des">
\<p class="original" **title="DryadBase_IntroResponse_Greymane00.ogg"**>DryadBase_IntroResponse_Greymane00.ogg\</p>
\<p class="text" **title="你不会在这些树上做标记吧？"**>你不会在这些树上做标记吧？\</p>
\</div>
\<div class="control">\<img src="image/iconfont-audio.png" style="width:20px">\</div>
\</div>

添加 title 属性以后，可以简单实现鼠标移上去显示全文的效果。

**Comment by khlipeng** [comment]
开开，这是什么项目啊？

**Comment by feifeiiiiiiiiiii** [comment]
业余玩的小玩意

2016-08-10 19:51 GMT+08:00 Li Peng <notifications@github.com>:
